"""
Harmonic sine-wave UDP sender for DHN pipeline bench testing.

Sends a multi-channel harmonic fingerprint that the DHN dashboard
receiver and dhn-udp-probe can verify in realtime.

Channel assignment (0-indexed):
  Ch 0  → f₁ only
  Ch 1  → f₁ + f₂
  Ch 2  → f₁ + f₂ + f₃
  Ch N  → f₁ … f_{N+1}

This is the same signal generated by the dashboard's "Harmonic Sine" source,
usable from the command line without starting the webapp.

Usage:
    dhn-sine-udp
    dhn-sine-udp --host 192.168.3.50 --port 26090
    dhn-sine-udp --channels 8 --fundamental 440 --sample-rate 32000 --duration 0
    dhn-sine-udp --dry-run
    dhn-sine-udp --help
"""

from __future__ import annotations

import time
from typing import Annotated, Optional

import numpy as np
import typer
from rich.console import Console
from rich.live import Live
from rich.table import Table

from darkhorse_neuralynx.udp_raw.raw_sender import RawUdpSender, SendStats, scale_to_int16

app = typer.Typer(
    help=(
        "Send a multi-channel harmonic sine fingerprint as headerless int16 UDP.\n\n"
        "Each channel carries successive harmonics of the fundamental frequency, "
        "making it easy to verify channel count and signal integrity at the receiver "
        "using FFT peak detection.\n\n"
        "Use dhn-udp-probe on the same or a remote host to monitor the incoming stream."
    ),
    add_completion=False,
)
console = Console()


def _build_harmonic_chunk(
    n_frames: int,
    n_channels: int,
    sample_rate: int,
    fundamental: float,
    t_offset: float,
) -> np.ndarray:
    """Return (n_frames, n_channels) float64 array in [-1, 1]."""
    t = np.arange(n_frames, dtype=np.float64) / sample_rate + t_offset
    out = np.zeros((n_frames, n_channels), dtype=np.float64)
    for ch in range(n_channels):
        n_harmonics = ch + 1
        for h in range(1, n_harmonics + 1):
            out[:, ch] += np.sin(2.0 * np.pi * fundamental * h * t)
        peak = np.max(np.abs(out[:, ch])) or 1.0
        out[:, ch] /= peak          # normalise to [-1, 1] so scaling is consistent
    return out


def _status_table(
    elapsed: float,
    duration: float,
    stats: SendStats,
    total_packets: int,
    total_bytes: int,
    total_underruns: int,
    channels: int,
    sr: int,
    fundamental: float,
    fpp: int,
    payload_bytes: int,
) -> Table:
    t = Table(show_header=False, box=None, padding=(0, 2))
    t.add_column("k", style="dim", min_width=26)
    t.add_column("v")
    dur_str = f"{duration:.0f} s" if duration > 0 else "∞  (Ctrl-C to stop)"
    t.add_row("Elapsed", f"{elapsed:.1f} s / {dur_str}")
    t.add_row("Channels", f"{channels}  (f₁={fundamental} Hz, each ch adds 1 harmonic)")
    t.add_row("Sample rate", f"{sr} Hz")
    t.add_row("Frames / packet", str(fpp))
    t.add_row("Payload bytes / pkt", f"{payload_bytes} bytes")
    t.add_row("Packet rate", f"{stats.effective_packet_rate:.0f} pkt/s")
    t.add_row("Throughput", f"{stats.effective_throughput_mbps:.4f} Mbit/s")
    t.add_row("Total packets", f"{total_packets:,}")
    t.add_row("Total bytes", f"{total_bytes:,}")
    t.add_row("Underruns", str(total_underruns))
    return t


@app.command()
def main(
    host: Annotated[str, typer.Option("--host", "-H", help="Destination UDP host")] = "127.0.0.1",
    port: Annotated[int, typer.Option("--port", "-p", help="Destination UDP port")] = 26090,
    channels: Annotated[int, typer.Option("--channels", "-c", help="Number of channels to send")] = 4,
    sample_rate: Annotated[int, typer.Option("--sample-rate", "-r", help="Sample rate in Hz")] = 32000,
    fundamental: Annotated[float, typer.Option("--fundamental", "-f", help="Fundamental frequency in Hz")] = 440.0,
    frames_per_packet: Annotated[int, typer.Option("--fpp", help="Frames per UDP packet")] = 1,
    target_peak: Annotated[int, typer.Option("--peak", help="Target int16 peak amplitude (0–32767)")] = 8000,
    send_buffer: Annotated[int, typer.Option("--send-buffer", help="UDP socket send buffer bytes")] = 8_388_608,
    duration: Annotated[float, typer.Option("--duration", "-d", help="Run duration in seconds (0 = infinite)")] = 0.0,
    chunk_seconds: Annotated[float, typer.Option("--chunk", help="Seconds of audio generated per loop iteration")] = 0.05,
    dry_run: Annotated[bool, typer.Option("--dry-run", help="Print parameters and exit without sending")] = False,
) -> None:
    """Send a harmonic sine fingerprint as headerless int16 UDP."""
    payload_bytes = frames_per_packet * channels * 2
    chunk_frames  = max(1, int(sample_rate * chunk_seconds))

    console.print("\n[bold cyan]DHN Harmonic Sine UDP Sender[/bold cyan]")
    console.print(f"  Destination   : [bold]{host}:{port}[/bold]")
    console.print(f"  Channels      : {channels}  (ch k carries harmonics f₁…f_{{k+1}})")
    console.print(f"  Fundamental   : {fundamental} Hz")
    console.print(f"  Sample rate   : {sample_rate} Hz")
    console.print(f"  Frames/packet : {frames_per_packet}")
    console.print(f"  Payload bytes : [bold]{payload_bytes}[/bold] bytes/pkt")
    console.print(f"  Duration      : {'infinite (Ctrl-C to stop)' if duration == 0 else f'{duration:.1f} s'}")

    if payload_bytes > 1400:
        console.print(
            f"  [yellow]WARNING[/yellow]: {payload_bytes} bytes > 1400-byte MTU "
            "— UDP fragmentation may occur unless jumbo frames are enabled."
        )

    if dry_run:
        console.print("\n[yellow]Dry-run — no packets sent.[/yellow]")
        return

    console.print()

    total_packets   = 0
    total_bytes     = 0
    total_underruns = 0
    t_start         = time.perf_counter()
    t_offset        = 0.0

    try:
        with RawUdpSender(host, port, send_buffer_bytes=send_buffer) as sender:
            with Live(console=console, refresh_per_second=4) as live:
                while True:
                    elapsed = time.perf_counter() - t_start
                    if duration > 0 and elapsed >= duration:
                        break

                    chunk = _build_harmonic_chunk(chunk_frames, channels, sample_rate, fundamental, t_offset)
                    chunk_int16 = scale_to_int16(chunk, target_peak=target_peak)

                    stats = sender.send_chunk(
                        chunk_int16,
                        sample_rate_hz=sample_rate,
                        frames_per_packet=frames_per_packet,
                        layout="sample_major",
                    )

                    total_packets   += stats.packets_sent
                    total_bytes     += stats.bytes_sent
                    total_underruns += stats.underruns
                    t_offset        += chunk_frames / sample_rate

                    live.update(
                        _status_table(
                            elapsed, duration, stats,
                            total_packets, total_bytes, total_underruns,
                            channels, sample_rate, fundamental,
                            frames_per_packet, payload_bytes,
                        )
                    )
    except KeyboardInterrupt:
        pass

    elapsed = time.perf_counter() - t_start
    console.print(
        f"\n[bold green]Done.[/bold green]  "
        f"Elapsed {elapsed:.1f} s  "
        f"Packets {total_packets:,}  "
        f"Bytes {total_bytes:,}  "
        f"Underruns {total_underruns}"
    )
